[tool.poetry]
name = "gilded-rose"
version = "0.1.0"
description = ""
authors = ["RadDini <radu.dinicescu@softwire.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
